=begin
    
    .	.	.	.	| ....
    .	.	.	.	| ....
    .	.	.	.	| ....
    .	.	.	.	| ....
    .	.	.	.	| ....
    .	.	.	.	| ....
    .	.	.	.	| ....
    .	.	.	.	| ....
    .	.	.	.	| ....
    .	.	.	.	| ....
    .	.	.	.	| ....
    .	.	.	.	| ....

    ---------------------------------
     Red Green Blue Yellow
    
=end

class Board; end

class KeyPeg; end

class CodePeg; end

class Color; end # check if there is anything built-in

class Computer; end


