=begin
    
    .	.	.	.	| ....
    .	.	.	.	| ....
    .	.	.	.	| ....
    .	.	.	.	| ....
    .	.	.	.	| ....
    .	.	.	.	| ....
    .	.	.	.	| ....
    .	.	.	.	| ....
    .	.	.	.	| ....
    .	.	.	.	| ....
    .	.	.	.	| ....
    .	.	.	.	| ....

    ---------------------------------
     Red Green Blue Yellow
    
=end

class Board
    def initialize
        @larger_board_array = Array.new(4, Array.new(4,'.  '))
        
    end
end



class Peg; end

class Color; end # check if there is anything built-in

class Computer; end


